apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-frontend
  labels:
    app: agentic-frontend
spec:
  replicas: {{ .Values.services.frontend.replicas }}
  selector:
    matchLabels:
      app: agentic-frontend
  template:
    metadata:
      labels:
        app: agentic-frontend
    spec:
      containers:
      - name: agentic-frontend
        image: {{ .Values.registry }}/{{ .Values.services.frontend.image }}
        ports:
        - containerPort: {{ .Values.services.frontend.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.frontend.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.services.frontend.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-frontend-service
  labels:
    app: agentic-frontend
spec:
  selector:
    app: agentic-frontend
  ports:
  - port: 80
    targetPort: {{ .Values.services.frontend.port }}
    protocol: TCP
  type: ClusterIP