apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mcp
  namespace: k8s-admin
  labels:
    app: k8s-mcp
spec:
  replicas: {{ .Values.services.k8sMcp.replicas }}
  selector:
    matchLabels:
      app: k8s-mcp
  template:
    metadata:
      labels:
        app: k8s-mcp
    spec:
      serviceAccountName: k8s-admin-service-account
      containers:
      - name: k8s-mcp
        image: {{ .Values.registry }}/{{ .Values.services.k8sMcp.image }}
        ports:
        - containerPort: {{ .Values.services.k8sMcp.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.k8sMcp.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.services.k8sMcp.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-mcp-service
  namespace: k8s-admin
  labels:
    app: k8s-mcp
spec:
  selector:
    app: k8s-mcp
  ports:
  - port: 80
    targetPort: {{ .Values.services.k8sMcp.port }}
    protocol: TCP
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-mcp-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mcp-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-mcp-cluster-role
subjects:
- kind: ServiceAccount
  name: k8s-admin-service-account
  namespace: k8s-admin